# Generated by Django 5.1.6 on 2025-02-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_alter_excel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='updatedat',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
