# Generated by Django 5.1.6 on 2025-02-19 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_alter_excel_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
