# Generated by Django 5.1.6 on 2025-02-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_alter_excel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excel',
            name='updatedat',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
